Added codespaces-enabled lab
srl-labs/intent-based-ansible-lab pull request #36
Opened 2024-07-12 11:42 UTC by FloSch62

Added codespace capabilities

2024-07-12 12:24 UTC, hellt commented on .devcontainer.json
> +    "image": "ghcr.io/srl-labs/containerlab/clab-devcontainer:0.55.0",
worth updating to 0.56.0

2024-07-12 12:26 UTC, hellt commented on .devcontainer.json
> +    "postCreateCommand": "sudo apt-get update && sudo apt-get install -y python3 python3-pip git && sudo pip3 install --upgrade pip && sudo pip3 install --ignore-installed ansible==8.3.0 ansible-core
maybe sudo for pip is not required?
also not sure if there are submodules in the repo that you update with the last command?
and if repo contains a requirements txt file it might be easier to install via this one

2024-07-12 13:14 UTC, FloSch62 commented on .devcontainer.json
> +    "image": "ghcr.io/srl-labs/containerlab/clab-devcontainer:0.55.0",
updated with #ca6be1c

2024-07-12 13:15 UTC, FloSch62 commented on .devcontainer.json
> +    "postCreateCommand": "sudo apt-get update && sudo apt-get install -y python3 python3-pip git && sudo pip3 install --upgrade pip && sudo pip3 install --ignore-installed ansible==8.3.0 ansible-core
updated with #ca6be1c

2024-07-15 11:52 UTC, hellt requested changes

2024-07-15 11:52 UTC, hellt commented on .devcontainer.json
> +    "onCreateCommand": "sudo apt-get update && sudo apt-get install -y python3 python3-pip git && pip3 install --upgrade pip && pip3 install -r requirements.txt && ansible-galaxy collection install n
Can you also add for the apt install --no-install-recommends. 
This will reduce the size and time substantially

2024-07-15 12:16 UTC, merged